export const ERROR_CODES = {
  VALIDATION_ERROR: 'VALIDATION_ERROR',

  USER_NOT_FOUND: 'USER_NOT_FOUND',
  POST_NOT_FOUND: 'POST_NOT_FOUND',
  AUTHOR_NOT_FOUND: 'AUTHOR_NOT_FOUND',

  EMAIL_ALREADY_EXISTS: 'EMAIL_ALREADY_EXISTS',
  USER_HAS_REFERENCES: 'USER_HAS_REFERENCES',
  POST_HAS_REFERENCES: 'POST_HAS_REFERENCES',

  USER_CREATION_ERROR: 'USER_CREATION_ERROR',
  USER_UPDATE_ERROR: 'USER_UPDATE_ERROR',
  USER_DELETION_ERROR: 'USER_DELETION_ERROR',
  POST_CREATION_ERROR: 'POST_CREATION_ERROR',
  POST_UPDATE_ERROR: 'POST_UPDATE_ERROR',
  POST_DELETION_ERROR: 'POST_DELETION_ERROR',
};
